/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoutsRouteImport } from './routes/bouts'
import { Route as CardRouteImport } from './routes/card'
import { Route as CeremonyRouteImport } from './routes/ceremony'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as HonorsRouteImport } from './routes/honors'
import { Route as HowRouteImport } from './routes/how'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewRouteImport } from './routes/new'
import { Route as ReportRouteImport } from './routes/report'
import { Route as RosterRouteImport } from './routes/roster'
import { Route as ScoreRouteImport } from './routes/score'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as LockerRouteImport } from './routes/locker'
import { Route as FighterIdRouteImport } from './routes/fighter.$id'
import { Route as PlaySlugRouteImport } from './routes/play.$slug'
import { Route as PrintIdRouteImport } from './routes/print.$id'
import { Route as RoomSlugRouteImport } from './routes/room.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutsRoute = BoutsRouteImport.update({
  id: '/bouts',
  path: '/bouts',
  getParentRoute: () => rootRouteImport,
} as any)
const CardRoute = CardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => rootRouteImport,
} as any)
const CeremonyRoute = CeremonyRouteImport.update({
  id: '/ceremony',
  path: '/ceremony',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const HonorsRoute = HonorsRouteImport.update({
  id: '/honors',
  path: '/honors',
  getParentRoute: () => rootRouteImport,
} as any)
const HowRoute = HowRouteImport.update({
  id: '/how',
  path: '/how',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterRoute = RosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreRoute = ScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const LockerRoute = LockerRouteImport.update({
  id: '/locker',
  path: '/locker',
  getParentRoute: () => rootRouteImport,
} as any)
const FighterIdRoute = FighterIdRouteImport.update({
  id: '/fighter/$id',
  path: '/fighter/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaySlugRoute = PlaySlugRouteImport.update({
  id: '/play/$slug',
  path: '/play/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintIdRoute = PrintIdRouteImport.update({
  id: '/print/$id',
  path: '/print/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomSlugRoute = RoomSlugRouteImport.update({
  id: '/room/$slug',
  path: '/room/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bouts': typeof BoutsRoute
  '/card': typeof CardRoute
  '/ceremony': typeof CeremonyRoute
  '/desk': typeof DeskRoute
  '/honors': typeof HonorsRoute
  '/how': typeof HowRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/report': typeof ReportRoute
  '/roster': typeof RosterRoute
  '/score': typeof ScoreRoute
  '/submit': typeof SubmitRoute
  '/locker': typeof LockerRoute
  '/fighter/$id': typeof FighterIdRoute
  '/play/$slug': typeof PlaySlugRoute
  '/print/$id': typeof PrintIdRoute
  '/room/$slug': typeof RoomSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bouts': typeof BoutsRoute
  '/card': typeof CardRoute
  '/ceremony': typeof CeremonyRoute
  '/desk': typeof DeskRoute
  '/honors': typeof HonorsRoute
  '/how': typeof HowRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/report': typeof ReportRoute
  '/roster': typeof RosterRoute
  '/score': typeof ScoreRoute
  '/submit': typeof SubmitRoute
  '/locker': typeof LockerRoute
  '/fighter/$id': typeof FighterIdRoute
  '/play/$slug': typeof PlaySlugRoute
  '/print/$id': typeof PrintIdRoute
  '/room/$slug': typeof RoomSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bouts': typeof BoutsRoute
  '/card': typeof CardRoute
  '/ceremony': typeof CeremonyRoute
  '/desk': typeof DeskRoute
  '/honors': typeof HonorsRoute
  '/how': typeof HowRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/report': typeof ReportRoute
  '/roster': typeof RosterRoute
  '/score': typeof ScoreRoute
  '/submit': typeof SubmitRoute
  '/locker': typeof LockerRoute
  '/fighter/$id': typeof FighterIdRoute
  '/play/$slug': typeof PlaySlugRoute
  '/print/$id': typeof PrintIdRoute
  '/room/$slug': typeof RoomSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bouts'
    | '/card'
    | '/ceremony'
    | '/desk'
    | '/honors'
    | '/how'
    | '/login'
    | '/new'
    | '/report'
    | '/roster'
    | '/score'
    | '/submit'
    | '/locker'
    | '/fighter/$id'
    | '/play/$slug'
    | '/print/$id'
    | '/room/$slug'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bouts'
    | '/card'
    | '/ceremony'
    | '/desk'
    | '/honors'
    | '/how'
    | '/login'
    | '/new'
    | '/report'
    | '/roster'
    | '/score'
    | '/submit'
    | '/locker'
    | '/fighter/$id'
    | '/play/$slug'
    | '/print/$id'
    | '/room/$slug'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/bouts'
    | '/card'
    | '/ceremony'
    | '/desk'
    | '/honors'
    | '/how'
    | '/login'
    | '/new'
    | '/report'
    | '/roster'
    | '/score'
    | '/submit'
    | '/locker'
    | '/fighter/$id'
    | '/play/$slug'
    | '/print/$id'
    | '/room/$slug'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoutsRoute: typeof BoutsRoute
  CardRoute: typeof CardRoute
  CeremonyRoute: typeof CeremonyRoute
  DeskRoute: typeof DeskRoute
  HonorsRoute: typeof HonorsRoute
  HowRoute: typeof HowRoute
  LoginRoute: typeof LoginRoute
  NewRoute: typeof NewRoute
  ReportRoute: typeof ReportRoute
  RosterRoute: typeof RosterRoute
  ScoreRoute: typeof ScoreRoute
  SubmitRoute: typeof SubmitRoute
  LockerRoute: typeof LockerRoute
  FighterIdRoute: typeof FighterIdRoute
  PlaySlugRoute: typeof PlaySlugRoute
  PrintIdRoute: typeof PrintIdRoute
  RoomSlugRoute: typeof RoomSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bouts': {
      id: '/bouts'
      path: '/bouts'
      fullPath: '/bouts'
      preLoaderRoute: typeof BoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card': {
      id: '/card'
      path: '/card'
      fullPath: '/card'
      preLoaderRoute: typeof CardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ceremony': {
      id: '/ceremony'
      path: '/ceremony'
      fullPath: '/ceremony'
      preLoaderRoute: typeof CeremonyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/honors': {
      id: '/honors'
      path: '/honors'
      fullPath: '/honors'
      preLoaderRoute: typeof HonorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how': {
      id: '/how'
      path: '/how'
      fullPath: '/how'
      preLoaderRoute: typeof HowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster': {
      id: '/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof RosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/score': {
      id: '/score'
      path: '/score'
      fullPath: '/score'
      preLoaderRoute: typeof ScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locker': {
      id: '/locker'
      path: '/locker'
      fullPath: '/locker'
      preLoaderRoute: typeof LockerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fighter/$id': {
      id: '/fighter/$id'
      path: '/fighter/$id'
      fullPath: '/fighter/$id'
      preLoaderRoute: typeof FighterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$slug': {
      id: '/play/$slug'
      path: '/play/$slug'
      fullPath: '/play/$slug'
      preLoaderRoute: typeof PlaySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/$id': {
      id: '/print/$id'
      path: '/print/$id'
      fullPath: '/print/$id'
      preLoaderRoute: typeof PrintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$slug': {
      id: '/room/$slug'
      path: '/room/$slug'
      fullPath: '/room/$slug'
      preLoaderRoute: typeof RoomSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoutsRoute: BoutsRoute,
  CardRoute: CardRoute,
  CeremonyRoute: CeremonyRoute,
  DeskRoute: DeskRoute,
  HonorsRoute: HonorsRoute,
  HowRoute: HowRoute,
  LoginRoute: LoginRoute,
  NewRoute: NewRoute,
  ReportRoute: ReportRoute,
  RosterRoute: RosterRoute,
  ScoreRoute: ScoreRoute,
  SubmitRoute: SubmitRoute,
  LockerRoute: LockerRoute,
  FighterIdRoute: FighterIdRoute,
  PlaySlugRoute: PlaySlugRoute,
  PrintIdRoute: PrintIdRoute,
  RoomSlugRoute: RoomSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
