/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoutsRouteImport } from './routes/bouts'
import { Route as CardRouteImport } from './routes/card'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewRouteImport } from './routes/new'
import { Route as ReportRouteImport } from './routes/report'
import { Route as RosterRouteImport } from './routes/roster'
import { Route as ScoreRouteImport } from './routes/score'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as FighterIdRouteImport } from './routes/fighter.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutsRoute = BoutsRouteImport.update({
  id: '/bouts',
  path: '/bouts',
  getParentRoute: () => rootRouteImport,
} as any)
const CardRoute = CardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterRoute = RosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreRoute = ScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const FighterIdRoute = FighterIdRouteImport.update({
  id: '/fighter/$id',
  path: '/fighter/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bouts': typeof BoutsRoute
  '/card': typeof CardRoute
  '/desk': typeof DeskRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/report': typeof ReportRoute
  '/roster': typeof RosterRoute
  '/score': typeof ScoreRoute
  '/submit': typeof SubmitRoute
  '/fighter/$id': typeof FighterIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bouts': typeof BoutsRoute
  '/card': typeof CardRoute
  '/desk': typeof DeskRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/report': typeof ReportRoute
  '/roster': typeof RosterRoute
  '/score': typeof ScoreRoute
  '/submit': typeof SubmitRoute
  '/fighter/$id': typeof FighterIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bouts': typeof BoutsRoute
  '/card': typeof CardRoute
  '/desk': typeof DeskRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/report': typeof ReportRoute
  '/roster': typeof RosterRoute
  '/score': typeof ScoreRoute
  '/submit': typeof SubmitRoute
  '/fighter/$id': typeof FighterIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bouts'
    | '/card'
    | '/desk'
    | '/login'
    | '/new'
    | '/report'
    | '/roster'
    | '/score'
    | '/submit'
    | '/fighter/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bouts'
    | '/card'
    | '/desk'
    | '/login'
    | '/new'
    | '/report'
    | '/roster'
    | '/score'
    | '/submit'
    | '/fighter/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/bouts'
    | '/card'
    | '/desk'
    | '/login'
    | '/new'
    | '/report'
    | '/roster'
    | '/score'
    | '/submit'
    | '/fighter/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoutsRoute: typeof BoutsRoute
  CardRoute: typeof CardRoute
  DeskRoute: typeof DeskRoute
  LoginRoute: typeof LoginRoute
  NewRoute: typeof NewRoute
  ReportRoute: typeof ReportRoute
  RosterRoute: typeof RosterRoute
  ScoreRoute: typeof ScoreRoute
  SubmitRoute: typeof SubmitRoute
  FighterIdRoute: typeof FighterIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bouts': {
      id: '/bouts'
      path: '/bouts'
      fullPath: '/bouts'
      preLoaderRoute: typeof BoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card': {
      id: '/card'
      path: '/card'
      fullPath: '/card'
      preLoaderRoute: typeof CardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster': {
      id: '/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof RosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/score': {
      id: '/score'
      path: '/score'
      fullPath: '/score'
      preLoaderRoute: typeof ScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fighter/$id': {
      id: '/fighter/$id'
      path: '/fighter/$id'
      fullPath: '/fighter/$id'
      preLoaderRoute: typeof FighterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoutsRoute: BoutsRoute,
  CardRoute: CardRoute,
  DeskRoute: DeskRoute,
  LoginRoute: LoginRoute,
  NewRoute: NewRoute,
  ReportRoute: ReportRoute,
  RosterRoute: RosterRoute,
  ScoreRoute: ScoreRoute,
  SubmitRoute: SubmitRoute,
  FighterIdRoute: FighterIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
